### ISSUE TITLE
If there are enough previous commands in the frame the completion menu does not work.

### ISSUE THREAD

**Issue by TiLopes** [abgox/PSCompletions#2]
![image](https://github.com/abgox/PSCompletions/assets/106965010/8e066631-66cb-4f41-a784-9b0b4c18fac9)
Is there any fallback? Otherwise it's pretty annoying since in most situations there are dozens of previous commands.

**Comment by abgox** [comment]
This is a limit to avoid accidental bugs in the previous unstable menu UI.
It is triggered only when the current input position is the last line of the terminal.
Due to my personal habits, I would not have such a situation, causing this issue to be forgotten and left to the present.
But for now, it really shouldn't exist.
I'll be dealing with it in the next version soon.

**Comment by abgox** [comment]
Version 3.0.7 has been released and the problem has been fixed.
