### ISSUE TITLE
[Bug]: update prompt displayed three times

### ISSUE THREAD

**Issue by soredake** [abgox/PSCompletions#55]
### Before Start

- [X] You are using the latest version of PSCompletions.
- [X] You have read this repository's README file.
- [X] You have search for related issues in [Issues](https://github.com/abgox/PSCompletions/issues).
- [X] You have visit https://pscompletions.pages.dev/

### What Powershell version are you using?

PowerShell

### What system are you using?

Windows

### Steps to reproduce

1) https://github.com/soredake/dotfiles_windows/blob/master/setup.ps1#L20
2) https://github.com/soredake/dotfiles_windows/blob/3ccd01ba2540df8d7ec16149193823eea980a2a4/dotfiles/OneDrive/Documents/PowerShell/Profile.ps1

### What is expected?

Update prompt should be displayed only one time.

### What is actually happening?

![изображение](https://github.com/user-attachments/assets/7b8d57b0-f47e-4376-9d8e-a4b69e9e7c6a)

**Comment by abgox** [comment]
- This is a compatibility issue with [CompletionPredictor](https://github.com/PowerShell/CompletionPredictor).
- In the following issue, I've explained that it just works together for now, but the module update confirmation message of [PSCompletions](https://github.com/abgox/PSCompletions) will still be displayed multiple times.
- https://github.com/PowerShell/CompletionPredictor/issues/37
- https://github.com/PowerShell/CompletionPredictor/issues/37#issuecomment-2342355297

**Comment by abgox** [comment]
- In fact, when [CompletionPredictor](https://github.com/PowerShell/CompletionPredictor) module is imported,in `init.ps1` in the [PSCompletions](https://github.com/abgox/PSCompletions) module, the method `$PSCompletions.write_with_color()` is executed three times when called each time.
- https://github.com/abgox/PSCompletions/blob/v5.1.2/module/PSCompletions/core/init.ps1#L645-L680
- But, when I turned the `$PSCompletions.write_with_color()` method into a  function (`function write_with_color {xxx}`) it went back to normal.
- It's not an expected behavior. For methods in objects, maybe [CompletionPredictor](https://github.com/PowerShell/CompletionPredictor) module has proxy or modify operations.

**Comment by abgox** [comment]
- fix it in #60
